name: PiMetaConnect Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  setup-and-maintenance:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for client and server dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install client dependencies
      - name: Install client dependencies
        run: |
          cd client
          yarn install

      # Step 4: Install server dependencies
      - name: Install server dependencies
        run: |
          cd server
          yarn install

      # Step 5: Install blockchain dependencies
      - name: Install blockchain dependencies
        run: |
          cd blockchain
          yarn install

      # Step 6: Deploy smart contracts
      - name: Deploy smart contracts
        run: |
          cd blockchain
          npx hardhat run scripts/deploy.js --network localhost

      # Step 7: Build the Unity metaverse project
      - name: Build Unity metaverse project
        run: |
          cd metaverse
          unity -batchmode -projectPath . -buildTarget WebGL -executeMethod BuildScript.Build

      # Step 8: Start Docker services
      - name: Start Docker services
        run: docker-compose up -d

      # Step 9: Clean up old logs and temporary files
      - name: Cleanup old files
        run: |
          bash scripts/cleanup-tremex.sh

      # Step 10: Verify and update dependencies weekly
      - name: Dependabot updates
        run: |
          bash scripts/create-pimetaconnect.sh
